-- Real guest list from Wedding List.xlsx (70 guests).
-- Supabase SQL Editor: paste → Run.

truncate table public.rsvps restart identity cascade;
truncate table public.guests restart identity cascade;

insert into public.guests (phone, email, first_name, last_name, addressee, name, tier)
values
  ('8327978346', 'j.ibarra1985@gmail.com', 'Joshua', 'Ibarra', 'The Ibarra Family', 'Joshua Ibarra', 'both'),
  ('8329717488', 'emerianos21@gmail.com', 'Eleni', 'Kramer', 'The Kramer Family', 'Eleni Kramer', 'both'),
  ('4238274000', 'nataliemwalker97@gmail.com', 'Natalie', 'Walker', 'Natalie Walker and Hunter Hambright', 'Natalie Walker', 'both'),
  ('8325663799', 'jesna93@yahoo.com', 'Jesna', 'Mathews', 'The Mathews Family', 'Jesna Mathews', 'both'),
  ('9794924118', 'racoffman@gmail.com', 'Rob', 'Coffman', 'The Rob Coffman', 'Rob Coffman', 'both'),
  ('2165389565', 'bianca.n.badescu@gmail.com', 'Bianca', 'Badescu', 'The Pogues', 'Bianca Badescu', 'both'),
  ('2146625555', 'ricardor@dallascoolpools.com', 'Ricardo', 'Rodriguez', 'The Rodriguez family', 'Ricardo Rodriguez', 'both'),
  ('8326332870', 'bethsorensen76@gmail.com', 'Beth and Carl', 'Sorensen', 'The Sorensen Family', 'Beth and Carl Sorensen', 'both'),
  ('2817321792', 'kevinwschott@gmail.com', 'Kevin', 'Schott', 'Schott Family', 'Kevin Schott', 'both'),
  ('8327416772', 'brandilisenbe@gmail.com', 'Brandi', 'Garcia', 'Bouzas Garcia Fam', 'Brandi Garcia', 'both'),
  ('9524121730', 'ktstubenrouch@gmail.com', 'Travis and Katelyn', 'Stubenrouch', 'The Stubenrouch Family', 'Travis and Katelyn Stubenrouch', 'both'),
  ('525626447440', 'luis11parra@gmail.com', 'Luis', 'Parra', 'The Parra''s', 'Luis Parra', 'both'),
  ('2817702719', 'robcerni@gmail.com', 'Rob', 'Erni', 'Rob Erni & Diandra Breen', 'Rob Erni', 'both'),
  ('6128893778', 'carl.hollimon@gmail.com', 'Carl', 'Hollimon', 'The Hollimon''s', 'Carl Hollimon', 'both'),
  ('3108445126', 'exayana8@gmail.com', 'Victor', 'Rodriguez', 'Victor Rodriguez and Family', 'Victor Rodriguez', 'both'),
  ('8324043499', 'hrod1964@sbcglobal.net', 'Hector', 'Rodriguez', 'Mr. & Mrs. Hector Rodriguez & family', 'Hector Rodriguez', 'both'),
  ('8326073778', 'berzayda@yahoo.com', 'Berzayda', 'Ochoa', 'The Rodriguez Family', 'Berzayda Ochoa', 'both'),
  ('6178958651', 'dmedinaarango@outlook.com', 'Daniela', 'Medina', 'The Medina Party', 'Daniela Medina', 'both'),
  ('7133046660', 'bspecto@gmail.com', 'Brian', 'Spector', 'Mr. & Mrs.', 'Brian Spector', 'both'),
  ('2818767882', 'sosamadalyn98@gmail.com', 'Maddy', 'Rahman', 'The Rahman Family', 'Maddy Rahman', 'both'),
  ('8323681922', 'jaclynd6@gmail.com', 'Jaclyn', 'Diaz', 'Jaclyn Diaz', 'Jaclyn Diaz', 'both'),
  ('3253403870', 'levi.lemaster@gmail.com', 'Levi', 'Lemaster', 'Lemaster Residence', 'Levi Lemaster', 'both'),
  ('4696443647', 'marksalvie@gmail.com', 'Mark', 'Salvie', 'The Salvie Family', 'Mark Salvie', 'both'),
  ('8327293364', 'nicolebhatnagar@gmail.com', 'Nicole', 'Bhatnagar', 'Nicole & Sina', 'Nicole Bhatnagar', 'both'),
  ('4106934525', 'm.arroyo20@gmail.com', 'Marco', 'Arroyo', 'Arroyo Topke', 'Marco Arroyo', 'both'),
  ('8326603434', 'timcaws@hotmail.com', 'Tim', 'Caws', 'Tim Caws', 'Tim Caws', 'both'),
  ('7132014409', 'rakheebdas@gmail.com', 'Rakhee', 'Das', 'Das', 'Rakhee Das', 'both'),
  ('7133781088', 'janelle90@hotmail.com', 'Gonzalo & Janelle', 'Ochoa', 'The Ochoa-Rosales Family', 'Gonzalo & Janelle Ochoa', 'both'),
  ('7138268731', 'sasharahman123@icloud.com', 'Sasha', 'Rahman', 'The Ramirez Family', 'Sasha Rahman', 'both'),
  ('9792045891', 'afmaqui@gmail.com', 'Agustin', 'Maqui', 'The Maqui Family', 'Agustin Maqui', 'both'),
  ('8327296266', 'sako@tajianent.com', 'Sako', 'Tajian', 'The Tajian Family', 'Sako Tajian', 'both'),
  ('9172940314', 'spellizzer@gmail.com', 'Sebastiano', 'Pellizzer', 'Pellizzer''s', 'Sebastiano Pellizzer', 'both'),
  ('7344762586', 'rick.d.rauser@gmail.com', 'Rick', 'Rauser', 'The Rausers', 'Rick Rauser', 'both'),
  ('7243163508', 'lauren.mcginnity@gmail.com', 'Lauren', 'McGinnity', 'Lauren McGinnity', 'Lauren McGinnity', 'both'),
  ('7134474591', 'kristeen.n.rodriguez@gmail.com', 'Kristeen', 'Joiner', 'Blake and Kristeen Joiner', 'Kristeen Joiner', 'both'),
  ('7138946687', 'jacsmith90@gmail.com', 'Jackson', 'Smith', 'Stephanie and Jackson Smith', 'Jackson Smith', 'both'),
  ('7134479685', 'jeff.brannigan@gmail.com', 'Jeff', 'Brannigan', 'Katie and Jeff Brannigan', 'Jeff Brannigan', 'both'),
  ('7135049708', 'rousyrod70@gmail.com', 'Mario', 'Rodriguez', 'The Rodriguez family', 'Mario Rodriguez', 'both'),
  ('2818146934', 'alrod33@hotmail.com', 'Albert', 'Rodriguez', 'Albert Rodriguez and Gabby Triveline', 'Albert Rodriguez', 'both'),
  ('7136287064', 'wesdillard@gmail.com', 'Wes', 'Dillard', 'Ashley & Wes Dillard', 'Wes Dillard', 'both'),
  ('8328510569', 'connorlwalsh@gmail.com', 'Connor', 'Walsh', 'Connor and Chae Eun', 'Connor Walsh', 'both'),
  ('8326128277', 'dane.thorwaldson@gmail.com', 'Dane', 'Thorwaldson', 'Dane Thorwaldson', 'Dane Thorwaldson', 'both'),
  ('7134431878', 'wells.ian@gmail.com', 'Ian', 'Wells', 'Ian Wells', 'Ian Wells', 'both'),
  ('7360601228', 'jerome.milongo@gmail.com', 'Jerome', 'Milongo', 'Natalia Rachlin and Jerome Milongo', 'Jerome Milongo', 'both'),
  ('8327941798', 'samihunt97@gmail.com', 'Samantha', 'Hunt', 'Samantha Hunt', 'Samantha Hunt', 'both'),
  ('7244178255', 'meganringledew@gmail.com', 'Andres', 'Marron', 'The Marron Family', 'Andres Marron', 'both'),
  ('4696443758', 'jsalvie@gmail.com', 'John', 'Salvie', 'The Salvie Family', 'John Salvie', 'both'),
  ('8324234571', 'kelgarci@gmail.com', 'Kelly', 'Garcia', 'Kelly Garcia and Taylor Hastings', 'Kelly Garcia', 'both'),
  ('2817066339', 'joses28sanchezfernandez@gmail.com', 'Jose', 'Sanchez', 'Sanchez Family', 'Jose Sanchez', 'both'),
  ('8328201130', 'jacobibarra@gmail.com', 'Jacob', 'Ibarra', 'Ibarra Fam', 'Jacob Ibarra', 'both'),
  ('7138281877', 'michael.bassila@gmail.com', 'michael', 'bassila', 'Bassila''s', 'michael bassila', 'both'),
  ('8324526796', 'pierce.bush@gmail.com', 'Pierce', 'Bush', 'The Bush Family', 'Pierce Bush', 'both'),
  ('7134800797', 'joshuaespinedo@gmail.com', 'Joshua', 'Espiñedo', 'Joshua Espiñedo', 'Joshua Espiñedo', 'both'),
  ('3305757872', 'englandcalais@gmail.com', 'England', 'Todd', 'England Todd and Patrick Butler', 'England Todd', 'both'),
  ('8324639446', 'blakeelliottlupton@gmail.com', 'Blake', 'Lupton', 'The Lupton''s', 'Blake Lupton', 'both'),
  ('7137572459', 'vela.acody@gmail.com', 'Cody', 'Vela', 'The Vela-Black Family', 'Cody Vela', 'both'),
  ('7134433398', 'george@georgejohnston.com', 'George Johnston + Jaime Loera', '', 'George + Jaime', 'George Johnston + Jaime Loera', 'both'),
  ('2817706153', 'sweetcaro98@live.com', 'Carolyn', 'Rodriguez', 'Carolyn Rodriguez', 'Carolyn Rodriguez', 'both'),
  ('8323871576', 'felipe.l.riccio@gmail.com', 'Felipe', 'Riccio', 'Riccio Family', 'Felipe Riccio', 'both'),
  ('8324849939', 'herrera.al.cr@gmail.com', 'Alejandro', 'Herrera', 'The Herrera''s', 'Alejandro Herrera', 'both'),
  ('7132568086', 'bobby@anvilhouston.com', 'Bobby', 'Heugel', 'Bobby Heugel', 'Bobby Heugel', 'both'),
  ('2819246360', 'brentnettles@gmail.com', 'Brent', 'Nettles', 'Brent Nettles', 'Brent Nettles', 'both'),
  ('7132568318', 'jharb@jharb.com', 'Justin', 'Harbison', 'Mr. and Mrs. Justin Harbison', 'Justin Harbison', 'both'),
  ('4158714536', 'zanepramirez@yahoo.com', 'Zane', 'Ramirez', 'Zane Ramirez', 'Zane Ramirez', 'both'),
  ('2816842620', 'tomlynchmusic@gmail.com', 'Tom', 'Lynch', 'The Lynches', 'Tom Lynch', 'both'),
  ('8323024437', 'grace@tinyboxwoods.com', 'Grace', 'Mihardja', 'Grace Mihardja', 'Grace Mihardja', 'both'),
  ('7138166619', 'bridgettfalcone@yahoo.com', 'Bridgett', 'Falcone', 'The Heisers', 'Bridgett Falcone', 'both'),
  ('8328146555', 'caralambright@yahoo.com', 'Cara', 'Lambright', 'Ms. Cara Lambright', 'Cara Lambright', 'both'),
  ('2027665636', 'willdanielsonlanier@gmail.com', 'Will', 'Danielson Lanier', 'Danielson Laniers', 'Will Danielson Lanier', 'both'),
  ('7328042996', 'lindsaybdouglas@gmail.com', 'Lindsay', 'Meir', 'The Meirs', 'Lindsay Meir', 'both');

-- Expected: 70 rows in public.guests